version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: PronostiqDb
      POSTGRES_USER: PostgrPronoDbUser
      POSTGRES_PASSWORD: SuperPassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - myapp-net

  pgloader:
    image: dimitri/pgloader
    command: pgloader /data/sqlite_to_postgres.load
    volumes:
      - E:/INFO/DjangoWebsite:/data
    networks:
      - myapp-net
    depends_on:
      - db

networks:
  myapp-net:

volumes:
  pgdata:
