# Generated by Django 5.2.1 on 2025-06-09 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(upload_to='teams')),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('date_started', models.DateTimeField(verbose_name='date started')),
                ('slug', models.SlugField(default='<django.db.models.fields.CharField>')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='players')),
                ('country', models.CharField(max_length=255)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esport.team')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateTimeField(verbose_name='date played')),
                ('duration', models.DurationField(blank=True)),
                ('slug', models.SlugField(default='<django.db.models.fields.CharField>')),
                ('blue_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blue_team', to='esport.team')),
                ('loser', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='loser_team', to='esport.team')),
                ('red_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='red_team', to='esport.team')),
                ('winner', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner_team', to='esport.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esport.tournament')),
            ],
        ),
    ]
