# Generated by Django 5.2.1 on 2025-06-14 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('esport', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prediction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='prediction',
            name='predicted_winner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predicted_match_wins', to='esport.team'),
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esport.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='blue_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blue_team', to='esport.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='loser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loser_team', to='esport.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='red_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='red_team', to='esport.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner_team', to='esport.team'),
        ),
        migrations.AddField(
            model_name='matchday',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='esport.tournament'),
        ),
        migrations.AddField(
            model_name='match',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esport.tournament'),
        ),
        migrations.AlterUniqueTogether(
            name='prediction',
            unique_together={('user', 'match')},
        ),
        migrations.AlterUniqueTogether(
            name='matchday',
            unique_together={('date', 'tournament')},
        ),
    ]
