# Generated by Django 5.2.1 on 2025-06-16 17:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esport', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='date_ended',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 16, 17, 20, 29, 833516, tzinfo=datetime.timezone.utc), verbose_name='date ended'),
            preserve_default=False,
        ),
    ]
