# Generated by Django 5.2.1 on 2025-06-09 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esport', '0002_alter_player_photo_alter_team_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='duration',
            field=models.DurationField(null=True),
        ),
    ]
