# Generated by Django 5.2.1 on 2025-06-09 21:08

from django.db import migrations, models
from datetime import timedelta


class Migration(migrations.Migration):

    dependencies = [
        ('esport', '0003_alter_match_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='duration',
            field=models.DurationField(blank=True, default=timedelta(minutes=5)),
        ),
    ]
