# Generated by Django 5.2.1 on 2025-06-16 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esport', '0003_tournament_date_ended'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='tournament',
        ),
    ]
