# Generated by Django 5.2.1 on 2025-07-03 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esport', '0004_remove_match_tournament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='photo',
            field=models.ImageField(upload_to='players'),
        ),
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.ImageField(upload_to='teams'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
