# Generated by Django 5.2.1 on 2025-07-11 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esport', '0009_match_scheduled_hour_alter_match_scheduled_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
