# Generated by Django 5.2.1 on 2025-07-11 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esport', '0010_match_is_closed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mvpdayvote',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='mvpdayvote',
            name='reset_id',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='mvpdayvote',
            unique_together={('user', 'match_day', 'fantasy_pick', 'reset_id')},
        ),
        migrations.CreateModel(
            name='MVPResetState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reset_id', models.PositiveIntegerField(default=0)),
                ('tournament', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='esport.tournament')),
            ],
        ),
    ]
