# Generated by Django 5.2.1 on 2025-07-15 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esport', '0011_alter_mvpdayvote_unique_together_mvpdayvote_reset_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='score_str',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
