# Generated by Django 5.2.1 on 2025-07-16 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esport', '0014_remove_match_blue_team_remove_match_red_team_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='blue_roster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blue_matches', to='esport.roster'),
        ),
        migrations.AlterField(
            model_name='match',
            name='red_roster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='red_matches', to='esport.roster'),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='roster_player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esport.rosterplayer'),
        ),
    ]
