# Generated by Django 5.2.1 on 2025-07-16 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esport', '0015_alter_match_blue_roster_alter_match_red_roster_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='date_ended',
            field=models.DateField(verbose_name='date ended'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='date_started',
            field=models.DateField(verbose_name='date started'),
        ),
    ]
