# Generated by Django 5.2.1 on 2025-07-16 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esport', '0016_alter_tournament_date_ended_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='liquipedia_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
