# Generated by Django 5.2.1 on 2025-07-18 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esport', '0017_tournament_liquipedia_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='golgg_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
