# Generated by Django 5.2.1 on 2025-07-18 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esport', '0018_match_golgg_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='scheduled_hour',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
