# Generated by Django 5.2.1 on 2025-07-19 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esport', '0019_alter_match_scheduled_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mvpdayvote',
            name='fantasy_pick',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esport.rosterplayer'),
        ),
    ]
