# Generated by Django 5.2.1 on 2025-07-21 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esport', '0020_alter_mvpdayvote_fantasy_pick'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerstats',
            name='match',
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_number', models.PositiveIntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esport.match')),
            ],
        ),
        migrations.AddField(
            model_name='playerstats',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='esport.game'),
        ),
    ]
