# Generated by Django 5.2.1 on 2025-07-22 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esport', '0022_game_loser_game_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='side_swapped',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='game',
            unique_together={('match', 'game_number')},
        ),
    ]
