# Generated by Django 5.2.1 on 2025-07-29 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esport', '0023_game_side_swapped_alter_game_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='teams'),
        ),
    ]
