# Generated by Django 5.2.1 on 2025-07-30 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esport', '0024_tournament_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='logo_dark',
            field=models.ImageField(blank=True, null=True, upload_to='tournaments'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='tournaments'),
        ),
    ]
