# Generated by Django 5.2.1 on 2025-08-04 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esport', '0026_remove_prediction_is_correct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='logo_dark',
            field=models.ImageField(blank=True, null=True, upload_to='teams'),
        ),
    ]
