# Generated by Django 5.2.1 on 2025-08-06 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esport', '0027_team_logo_dark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='region',
        ),
        migrations.AddField(
            model_name='player',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='team',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='league',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='split',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='players'),
        ),
    ]
