# Generated by Django 5.2.1 on 2026-04-16 14:46

import esport.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esport', '0028_remove_tournament_region_player_slug_team_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='aliases',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='champion',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=esport.utils.OverwriteStorage(), upload_to='champions'),
        ),
        migrations.AlterField(
            model_name='player',
            name='photo',
            field=models.ImageField(blank=True, null=True, storage=esport.utils.OverwriteStorage(), upload_to='players'),
        ),
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.ImageField(storage=esport.utils.OverwriteStorage(), upload_to='teams'),
        ),
        migrations.AlterField(
            model_name='team',
            name='logo_dark',
            field=models.ImageField(blank=True, null=True, storage=esport.utils.OverwriteStorage(), upload_to='teams'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='logo',
            field=models.ImageField(blank=True, null=True, storage=esport.utils.OverwriteStorage(), upload_to='tournaments'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='logo_dark',
            field=models.ImageField(blank=True, null=True, storage=esport.utils.OverwriteStorage(), upload_to='tournaments'),
        ),
    ]
