# Generated by Django 5.2.1 on 2026-04-18 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esport', '0029_player_aliases_alter_champion_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='lp_slug',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
    ]
